/**
 ******************************************************************************
 * @file           : lib.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Library body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "AILib.h"
#include "stm32l4xx_hal.h"

/** Functions ----------------------------------------------------------------*/
	void AIInit(void) {

	}

	uint8_t AILearn(float data_input[]) {
	    HAL_Delay(20);
		return 1;
	}

	uint8_t AIDetect(float data_input[]) {
		return 100;
	}

	void AISetSensitivity(float sensitivity) {

	}

	float AIGetSensitivity(void) {
		return 1.0f;
	}

