/**
 ******************************************************************************
 * @file           : lib.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Library body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "NanoEdgeAI.h"
#include "stm32l4xx_hal.h"

/** Functions ----------------------------------------------------------------*/
	void NanoEdgeAI_initialize(void) {

	}

	uint8_t NanoEdgeAI_learn(float data_input[]) {
	    HAL_Delay(20);
		return 1;
	}

	uint8_t NanoEdgeAI_detect(float data_input[]) {
		return 100;
	}

	void NanoEdgeAI_set_sensitivity(float sensitivity) {

	}

	float NanoEdgeAI_get_sensitivity(void) {
		return 1.0f;
	}

	void NanoEdgeAI_forecasting_set_limit(float min_value, float max_value) {

	}

	void NanoEdgeAI_forecasting_push(float value) {

	}

	void NanoEdgeAI_forecasting_get(float forecast[], uint32_t n_step) {

	}
//  for freeRTOS ??????
//void xPortSysTickHandler( void )
//{
//
//}
